seeder: 
  file: ./seeder/seeder.rb
  disabled: false


parsers:
  - file: ./parsers/product.rb
    disabled: true
    page_type: search

  - file: ./parsers/search.rb
    disabled: true 
    page_type: product