seeder: 
  file: ./seeder/seeder.rb
  disabled: false


parsers:
  - file: ./parsers/product.rb
    disabled: false
    page_type: product

  - file: ./parsers/search.rb
    disabled: false
    page_type: search